[package]
name = "rust_ffi"
version = "0.1.0"
edition = "2018"

[lib]
name = "rust_ffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
uniffi = "0.21.0"
uniffi_macros = "0.21.0"

[build-dependencies]
uniffi_build = {version="0.21.0", features = ["builtin-bindgen"] }
